### ISSUE TITLE
Undefined is not an object 

### ISSUE THREAD

**Issue by cchamnab** [stoffern/react-native-mediapicker#4]
I got following error when trying to use : 

`Undefined is not an object (evaluating 'RCTCameraRollManager.getPhotos')`

**Comment by st0ffern** [comment]
Did you set: groupTypes and assetType ?

**Comment by st0ffern** [comment]
@choungchamnab did you solve this?

**Comment by cpjolicoeur** [comment]
I have the same error currently.  I did have `assetType`  set, but not `groupTypes`.  Both are listed as optional in the docs though.  I then tried by specifying both `assetType` and `groupTypes` and still had the same error.

```TypeError: Cannot read property 'getPhotos' of undefined```

Thrown in `MediaPicker`

**Comment by cpjolicoeur** [comment]
Actually, I believe this issue was just related to not linking the RCTCameraRoll library in iOS.  False alarm.  I'd suspect @choungchamnab has the same issue.
